added dtos and controllers
NikitaLafinskiy/book-store pull request #1
Opened 2024-09-18 10:16 UTC by NikitaLafinskiy

2024-09-18 12:28 UTC, Elena-Bruyako requested changes
see comments

2024-09-18 12:28 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/Book.java
> +@Data
It should be done by previous HW

```suggestion
@Getter
@Setter
@Table....
```

2024-09-18 12:28 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/repository/BookRepositoryImpl.java
> +@Repository
Add Lombok annotation instead of generating constructor by yourself

2024-09-18 12:28 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/BookServiceImpl.java
> +        Book book = bookRepository.getById(id);
```suggestion
        Book book = bookRepository.findById(id).orElseThrow();
```

You should use findById and return Optional

2024-09-18 12:28 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/BookServiceImpl.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2024-09-19 07:16 UTC, liliia-ponomarenko approved these changes
Please ensure that only those changes relevant to the current task are displayed in your PR. To do this, you can change the value of `base` to the previous branch.

2024-09-19 07:16 UTC, liliia-ponomarenko commented on src/main/java/com/bookstore/repository/BookRepositoryImpl.java
> +            throw new EntityNotFoundException("Unable to save the book: " + book, e);
You should use DataProcessingException(message, e). EntityNotFoundException is not a relevant error in this case. (same for other methods of this class. But you can ignore this comment because these methods will be replaced in the next task)).

2024-09-19 17:33 UTC, merged