added liquibase, changed the repository implementation
NikitaLafinskiy/book-store pull request #2
Opened 2024-09-19 18:31 UTC by NikitaLafinskiy

2024-09-20 08:31 UTC, ahoienko requested changes
One of requirements is not implemented (Change spring.jpa.hibernate.ddl-auto property value to validate)

2024-09-21 08:05 UTC, NikitaLafinskiy commented
> One of requirements is not implemented (Change spring.jpa.hibernate.ddl-auto property value to validate)

I did change it but I do not want to commit my application.properties file, it has a value of:
spring.jpa.hibernate.ddl-auto=validate

2024-09-22 17:03 UTC, sarakhmen requested changes
let's improve your solution :)

2024-09-22 17:03 UTC, sarakhmen commented on src/main/java/com/bookstore/controller/BookController.java
> +    @PutMapping("{id}")
```suggestion
    @PutMapping("/{id}")
```
fix in all places

2024-09-22 17:03 UTC, sarakhmen commented on src/main/java/com/bookstore/controller/BookController.java
> +        return "Deleted a book with an id of " + id;
let's not return any strings from this method. Simply annotate it with  @ResponseStatus(value = HttpStatus.NO_CONTENT)

2024-09-23 12:45 UTC, Elena-Bruyako requested changes
see comments

2024-09-23 12:45 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/controller/BookController.java
> +    public String deleteBookById(@PathVariable Long id) {
```suggestion
    public void deleteBookById(@PathVariable Long id) {
```

2024-09-23 12:45 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/controller/BookController.java
> +        return "Deleted a book with an id of " + id;
```suggestion
```

2024-09-23 12:45 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/Book.java
> +@Where(clause = "is_deleted = false")
check if Where isn't deprecated

2024-09-23 12:45 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/BookServiceImpl.java
> +        book.setId(id);
```suggestion
        bookMapper.updateBookFromDto(createBookRequestDto, book);
```

2024-09-23 12:45 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-book-init.yaml
> +                  defaultValueBoolean: false
```suggestion
                  defaultValueBoolean: false
                  constraints:
                      nullable: false
```

2024-09-23 12:45 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-book-init.yaml
> +            defaultValueBoolean: false
```suggestion
```

2024-09-23 12:45 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: classpath:db/changelog/changes/01-book-init.yaml
```suggestion
      file: classpath:db/changelog/changes/01-create-books-table.yaml
```

2024-09-23 13:40 UTC, Elena-Bruyako requested changes

2024-09-23 13:40 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/Book.java
> +    private Boolean isDeleted;
```suggestion
    private boolean isDeleted;
```

2024-09-23 13:40 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/BookServiceImpl.java
> +        Book book = bookMapper.updateBookFromDto(createBookRequestDto, id);
```suggestion
        Book book = bookRepository.findById(id).orElseThrow...
        bookMapper.updateBookFromDto(createBookRequestDto, book);
```

2024-09-23 13:40 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/mapper/BookMapper.java
> +    Book updateBookFromDto(CreateBookRequestDto createBookRequestDto, Long id);
```suggestion
    void updateBookFromDto(CreateBookRequestDto book, @MappingTarget Book entity);
```

2024-09-24 13:55 UTC, Elena-Bruyako requested changes

2024-09-24 13:55 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/BookServiceImpl.java
> +        book = bookMapper.updateBookFromDto(createBookRequestDto, book);
```suggestion
        bookMapper.updateBookFromDto(createBookRequestDto, book);
```

2024-09-24 13:55 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/mapper/BookMapper.java
> +    Book updateBookFromDto(CreateBookRequestDto createBookRequestDto, @MappingTarget Book book);
```suggestion
    void updateBookFromDto(CreateBookRequestDto createBookRequestDto, @MappingTarget Book book);
```

2024-09-25 13:03 UTC, Elena-Bruyako approved these changes

2024-09-25 16:32 UTC, merged